apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
      - name: review-service
        image: review-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: "redis-reviews"
---
apiVersion: v1
kind: Service
metadata:
  name: review-service
spec:
  selector:
    app: review-service
  ports:
  - port: 80
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-reviews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-reviews
  template:
    metadata:
      labels:
        app: redis-reviews
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-reviews
spec:
  selector:
    app: redis-reviews
  ports:
  - port: 6379
